# permissions for end users to view requestroutingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: requestroutingrules-viewer-role
rules:
- apiGroups:
  - arc.azure.com
  resources:
  - requestroutingrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arc.azure.com
  resources:
  - requestroutingrules/status
  verbs:
  - get
