# permissions for end users to edit requestroutingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: requestroutingrules-editor-role
rules:
- apiGroups:
  - arc.azure.com
  resources:
  - requestroutingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arc.azure.com
  resources:
  - requestroutingrules/status
  verbs:
  - get
